version: "3.8"

services:
  proxy-front:
    networks:
      - net
  front:
    networks:
      - net
  projects-front:
    networks:
      - net
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL?Place url to projects backend in REACT_APP_API_URL}
networks:
  net:
    driver: overlay2
