version: "3.8"

services:
  proxy-front:
    build: deploy
    ports:
      - 9000:9000
  front:
    build: ITLab-Front/deploy
  projects-front:
    build: ITLab-Projects-Front/deploy
    ports:
      - 9002:9002
